#   ############################################################
#   # +------------------------------------------------------+ #
#   # |              MobGun Main Configuration               | #
#   # +------------------------------------------------------+ #
#   ############################################################

Prefix: '&9&lMOBGUNS &4&l> &a'
Pig-Launched: 'Pig Launched !'
Sheep-Launched: 'Sheep Launched !'
Creeper-Launched: 'Creeper Launched !'
Villager-Launched: 'Villager Launched !'
Gun-Ready: 'You can now use again your gun !'
Wait-Before-Using-Again: '&cwait 5 seconds before each use !'
Config-Reloaded: '&aConfig reloaded !'


